// Application schema v12: structural contract, generated from the existing bootstrap and migrations.
// Column order and CREATE formatting are intentionally not part of compatibility.
export const APPLICATION_SCHEMA_VERSION = 12;

export const APPLICATION_TABLES = [
  "chat_messages",
  "compatibility_checks",
  "consultation_requests",
  "consultation_slots",
  "daily_landing",
  "feedback",
  "profiles",
  "readings",
  "schema_version",
  "settings",
  "users",
] as const;
export const APPLICATION_COLUMNS = [
  ["chat_messages", "check_id", "TEXT", 0, null, 0],
  ["chat_messages", "content", "TEXT", 1, null, 0],
  ["chat_messages", "created_at", "TEXT", 1, null, 0],
  ["chat_messages", "id", "TEXT", 0, null, 1],
  ["chat_messages", "model", "TEXT", 0, null, 0],
  ["chat_messages", "profile_id", "TEXT", 0, null, 0],
  ["chat_messages", "rated_at", "TEXT", 0, null, 0],
  ["chat_messages", "rating", "INTEGER", 0, null, 0],
  ["chat_messages", "role", "TEXT", 1, null, 0],
  ["chat_messages", "session_id", "TEXT", 1, "''", 0],
  ["chat_messages", "session_type", "TEXT", 1, null, 0],
  ["chat_messages", "user_id", "TEXT", 1, null, 0],
  ["compatibility_checks", "created_at", "TEXT", 1, null, 0],
  ["compatibility_checks", "id", "TEXT", 0, null, 1],
  ["compatibility_checks", "profile_id_1", "TEXT", 1, null, 0],
  ["compatibility_checks", "profile_id_2", "TEXT", 1, null, 0],
  ["compatibility_checks", "result_json", "TEXT", 1, null, 0],
  ["compatibility_checks", "score", "REAL", 1, null, 0],
  ["compatibility_checks", "user_id", "TEXT", 1, null, 0],
  ["consultation_requests", "admin_note", "TEXT", 0, null, 0],
  ["consultation_requests", "amount_paise", "INTEGER", 0, null, 0],
  ["consultation_requests", "answered_at", "TEXT", 0, null, 0],
  ["consultation_requests", "constraint_text", "TEXT", 1, null, 0],
  ["consultation_requests", "created_at", "TEXT", 1, null, 0],
  ["consultation_requests", "delivery_mode", "TEXT", 1, null, 0],
  ["consultation_requests", "id", "TEXT", 0, null, 1],
  ["consultation_requests", "life_area", "TEXT", 1, null, 0],
  ["consultation_requests", "objective", "TEXT", 1, null, 0],
  ["consultation_requests", "observation", "TEXT", 1, null, 0],
  ["consultation_requests", "options", "TEXT", 0, null, 0],
  ["consultation_requests", "profile_ids", "TEXT", 1, null, 0],
  ["consultation_requests", "slot_starts_at", "TEXT", 0, null, 0],
  ["consultation_requests", "status", "TEXT", 1, "'pending'", 0],
  ["consultation_requests", "user_feedback_note", "TEXT", 0, null, 0],
  ["consultation_requests", "user_id", "TEXT", 1, null, 0],
  ["consultation_requests", "user_rating", "TEXT", 0, null, 0],
  ["consultation_slots", "id", "TEXT", 0, null, 1],
  ["consultation_slots", "is_booked", "INTEGER", 1, "0", 0],
  ["consultation_slots", "starts_at", "TEXT", 1, null, 0],
  ["daily_landing", "attempts", "INTEGER", 1, "0", 0],
  ["daily_landing", "created_at", "TEXT", 1, null, 0],
  ["daily_landing", "generated_at", "TEXT", 0, null, 0],
  ["daily_landing", "id", "TEXT", 0, null, 1],
  ["daily_landing", "ist_date", "TEXT", 1, null, 0],
  ["daily_landing", "last_attempt_at", "TEXT", 0, null, 0],
  ["daily_landing", "payload", "TEXT", 0, null, 0],
  ["feedback", "created_at", "TEXT", 1, null, 0],
  ["feedback", "id", "TEXT", 0, null, 1],
  ["feedback", "message", "TEXT", 0, null, 0],
  ["feedback", "page_url", "TEXT", 0, null, 0],
  ["feedback", "rating", "TEXT", 1, null, 0],
  ["feedback", "user_email", "TEXT", 0, null, 0],
  ["profiles", "created_at", "TEXT", 1, null, 0],
  ["profiles", "current_latitude", "REAL", 0, null, 0],
  ["profiles", "current_location", "TEXT", 0, null, 0],
  ["profiles", "current_longitude", "REAL", 0, null, 0],
  ["profiles", "current_timezone", "TEXT", 0, null, 0],
  ["profiles", "current_timezone_offset", "REAL", 0, null, 0],
  ["profiles", "date_of_birth", "TEXT", 1, null, 0],
  ["profiles", "gender", "TEXT", 0, null, 0],
  ["profiles", "id", "TEXT", 0, null, 1],
  ["profiles", "latitude", "REAL", 1, null, 0],
  ["profiles", "longitude", "REAL", 1, null, 0],
  ["profiles", "name", "TEXT", 1, null, 0],
  ["profiles", "place_of_birth", "TEXT", 1, null, 0],
  ["profiles", "relationship", "TEXT", 0, null, 0],
  ["profiles", "time_of_birth", "TEXT", 1, null, 0],
  ["profiles", "timezone", "TEXT", 1, null, 0],
  ["profiles", "timezone_offset", "REAL", 1, null, 0],
  ["profiles", "user_id", "TEXT", 1, null, 0],
  ["readings", "created_at", "TEXT", 1, null, 0],
  ["readings", "engine", "TEXT", 1, null, 0],
  ["readings", "id", "TEXT", 0, null, 1],
  ["readings", "input_snapshot", "TEXT", 1, null, 0],
  ["readings", "output_data", "TEXT", 1, null, 0],
  ["readings", "profile_id", "TEXT", 1, null, 0],
  ["readings", "rated_at", "TEXT", 0, null, 0],
  ["readings", "rating", "INTEGER", 0, null, 0],
  ["schema_version", "id", "INTEGER", 0, "1", 1],
  ["schema_version", "version", "INTEGER", 1, "0", 0],
  ["settings", "key", "TEXT", 0, null, 1],
  ["settings", "updated_at", "TEXT", 1, null, 0],
  ["settings", "value", "TEXT", 1, null, 0],
  ["users", "created_at", "TEXT", 0, null, 0],
  ["users", "email", "TEXT", 0, null, 0],
  ["users", "id", "TEXT", 0, null, 1],
  ["users", "image", "TEXT", 0, null, 0],
  ["users", "last_login", "TEXT", 0, null, 0],
  ["users", "name", "TEXT", 0, null, 0],
] as const;
export const APPLICATION_INDEXES = [
  [
    "chat_messages",
    "idx_chat_messages_session",
    0,
    "c",
    0,
    0,
    "session_id",
    "BINARY",
    0,
  ],
  [
    "chat_messages",
    "idx_chat_messages_user",
    0,
    "c",
    0,
    0,
    "user_id",
    "BINARY",
    0,
  ],
  [
    "chat_messages",
    "idx_chat_messages_user",
    0,
    "c",
    0,
    1,
    "created_at",
    "BINARY",
    0,
  ],
  [
    "chat_messages",
    "sqlite_autoindex_chat_messages_1",
    1,
    "pk",
    0,
    0,
    "id",
    "BINARY",
    0,
  ],
  [
    "compatibility_checks",
    "idx_compatibility_user",
    0,
    "c",
    0,
    0,
    "user_id",
    "BINARY",
    0,
  ],
  [
    "compatibility_checks",
    "sqlite_autoindex_compatibility_checks_1",
    1,
    "pk",
    0,
    0,
    "id",
    "BINARY",
    0,
  ],
  [
    "consultation_requests",
    "idx_consultation_requests_user",
    0,
    "c",
    0,
    0,
    "user_id",
    "BINARY",
    0,
  ],
  [
    "consultation_requests",
    "idx_consultation_requests_user",
    0,
    "c",
    0,
    1,
    "status",
    "BINARY",
    0,
  ],
  [
    "consultation_requests",
    "sqlite_autoindex_consultation_requests_1",
    1,
    "pk",
    0,
    0,
    "id",
    "BINARY",
    0,
  ],
  [
    "consultation_slots",
    "idx_slots_starts_at",
    0,
    "c",
    0,
    0,
    "starts_at",
    "BINARY",
    0,
  ],
  [
    "consultation_slots",
    "sqlite_autoindex_consultation_slots_1",
    1,
    "pk",
    0,
    0,
    "id",
    "BINARY",
    0,
  ],
  [
    "daily_landing",
    "idx_daily_landing_generated",
    0,
    "c",
    0,
    0,
    "generated_at",
    "BINARY",
    0,
  ],
  [
    "daily_landing",
    "sqlite_autoindex_daily_landing_1",
    1,
    "pk",
    0,
    0,
    "id",
    "BINARY",
    0,
  ],
  [
    "daily_landing",
    "sqlite_autoindex_daily_landing_2",
    1,
    "u",
    0,
    0,
    "ist_date",
    "BINARY",
    0,
  ],
  ["feedback", "sqlite_autoindex_feedback_1", 1, "pk", 0, 0, "id", "BINARY", 0],
  ["profiles", "idx_profiles_user", 0, "c", 0, 0, "user_id", "BINARY", 0],
  ["profiles", "sqlite_autoindex_profiles_1", 1, "pk", 0, 0, "id", "BINARY", 0],
  ["readings", "idx_readings_lookup", 0, "c", 0, 0, "profile_id", "BINARY", 0],
  ["readings", "idx_readings_lookup", 0, "c", 0, 1, "engine", "BINARY", 0],
  ["readings", "idx_readings_profile", 0, "c", 0, 0, "profile_id", "BINARY", 0],
  ["readings", "sqlite_autoindex_readings_1", 1, "pk", 0, 0, "id", "BINARY", 0],
  [
    "settings",
    "sqlite_autoindex_settings_1",
    1,
    "pk",
    0,
    0,
    "key",
    "BINARY",
    0,
  ],
  ["users", "sqlite_autoindex_users_1", 1, "pk", 0, 0, "id", "BINARY", 0],
  ["users", "sqlite_autoindex_users_2", 1, "u", 0, 0, "email", "BINARY", 0],
] as const;
