import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// `eslint-config-next/core-web-vitals` already declares the `jsx-a11y` plugin
// and its recommended rules. Importing `eslint-plugin-jsx-a11y` again and
// spreading `.flatConfigs.recommended` (as PR #66 originally did) triggers
// "Cannot redefine plugin 'jsx-a11y'". We keep the rules but don't double-add
// the plugin.
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build artefact (generated by `npm run prebuild`):
    "lib/content/content-index.json",
  ]),
]);

export default eslintConfig;
